apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-k8s-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ntchinda-Giscard/k8s.git
    targetRevision: HEAD # You can change this to 'main' or a specific branch/tag
    path: k8s # Now pointing to the specific folder
  destination:
    server: https://kubernetes.default.svc
    namespace: default # Replace with the namespace where you want your apps deployed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
