apiVersion: v1
kind: PersistentVolume
metadata:
  name: wazalink-sqlite-pv
  labels:
    app: wazalink
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/wazalink
    type: DirectoryOrCreate
