apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazalink-sqlite-pvc
  namespace: default
  labels:
    app: wazalink
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: manual
