apiVersion: v1
kind: Secret
metadata:
  name: my-private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/Ntchinda-Giscard/k8s.git
  username: Ntchinda-Giscard
  password: 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
