apiVersion: v1
kind: Secret
metadata:
  name: wazalink-secret
  namespace: default
  labels:
    app: wazalink
type: Opaque
# stringData allows providing secrets in cleartext, which Kubernetes automatically base64-encodes upon creation
stringData:
  # Sage Syracuse Web Service Authentication
  X3_WEBSERVICE_WEBSERVICE_USERNAME: "Admin"
  X3_WEBSERVICE_WEBSERVICE_PASSWORD: "Wazasolutions@2025"

  # Sage HRM SQL Server Database Credentials
  SAGE_HRM_USERNAME: "wazalink"
  SAGE_HRM_PASSWORD: "Waza#Lnk!Secure2026"

  # Sage X3 SQL Server Database Credentials
  SAGE_X3_USERNAME: "wazalink"
  SAGE_X3_PASSWORD: "Waza#Lnk!Secure2026"

  # Base state database credentials (optional placeholders)
  DATABASE_USERNAME: "wazalink"
  DATABASE_PASSWORD: ""
