apiVersion: v1
kind: ConfigMap
metadata:
  name: wazalink-config
  namespace: default
  labels:
    app: wazalink
data:
  SENTRY_DSN: "https://f331e443af167a15d29686db1238a11d@o4511144775188480.ingest.de.sentry.io/4511270211682384"
  # OpenSSL configuration for legacy SQL Server TLS compatibility
  OPENSSL_CONF: "/etc/ssl/openssl.cnf"
  # Sage Syracuse Web Service Endpoint
  X3_WS_URL: "http://192.168.99.13:8124/soap-generic/syracuse/collaboration/syracuse/CAdxWebServiceXmlCC"
  X3_WS_POOL: "ZOPALM"
  X3_WS_LANG: "FRA"

  # Sage HRM SQL Server Database Configuration
  HRM_DB_DRIVER: "ODBC Driver 17 for SQL Server"
  HRM_DB_SERVER: "192.168.99.22,1435"
  HRM_DB_DATABASE: "x3ppleprod"
  HRM_DB_TRUST_CERTIFICATE: "yes"

  # Sage X3 SQL Server Database Configuration
  X3_DB_DRIVER: "ODBC Driver 18 for SQL Server"
  X3_DB_SERVER: "192.168.99.13,1434"
  X3_DB_DATABASE: "sage"
  X3_DB_TRUST_CERTIFICATE: "yes"

  # CAPI Client Endpoint
  CAPI_URL: "http://192.168.100.2"
