apiVersion: v1
kind: Secret
metadata:
  name: wazalink-secret
  namespace: default
  labels:
    app: wazalink
type: Opaque
# stringData allows providing secrets in cleartext, which Kubernetes automatically base64-encodes upon creation
stringData:
  # Sage Syracuse Web Service Authentication
  X3_WS_USERNAME: "admin"
  X3_WS_PASSWORD: "SOPA@2603ek@"

  # Sage HRM SQL Server Database Credentials
  HRM_DB_USERNAME: "zwaza1"
  HRM_DB_PASSWORD: "Waza#Lnk!Secure2026"

  # Sage X3 SQL Server Database Credentials
  X3_DB_USERNAME: "zwaza"
  X3_DB_PASSWORD: "Waza#Lnk!Secure2026"

  # API Protection Key
  API_KEY: "5eb2551165f9b9823cb144c7d08131abae734911d94b727c2a8e824183ee2394"

  # Sentry DSN (optional)
  SENTRY_DSN: "https://f331e443af167a15d29686db1238a11d@o4511144775188480.ingest.de.sentry.io/4511270211682384"
