apiVersion: v1
kind: Service
metadata:
  name: wazalink-service
  namespace: default
  labels:
    app: wazalink
spec:
  selector:
    app: wazalink
  # Expose as a NodePort so it's accessible outside the cluster
  type: NodePort
  ports:
    - name: http
      port: 7636
      targetPort: 7636
      nodePort: 30080
      protocol: TCP
