apiVersion: v1
kind: Service
metadata:
  name: wazalink-service-nodeport
  namespace: default
  labels:
    app: wazalink
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.100.2"
spec:
  selector:
    app: wazalink
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 30080 # External port
      targetPort: 7636 # Container port
      protocol: TCP
